### ISSUE TITLE
CartoDBfy is incomplete for GDAL/OGR Driver CSV import using GDAL 2.1.2

### ISSUE THREAD

**Issue by ztephm** [CartoDB/gdal#3]
@rafatower
cc @jsanz 

Remember [this issue](https://github.com/CartoDB/gdal/issues/2)? CARTO GDAL driver was fixed so that shapefiles import properly now.

However CSV imports do not Cartodbfy. 

## Context
It's a little different than previous issue. Last time the_geom_webmercator column was created, but had null values upon shapefile import. Now there is no the_geom_webmercator column created upon CSV import.

Looks like partial Cartodbfy is happening b/c a cartodb_id column is created.

- account = stephaniemongon
- I used [these csvs to test](https://github.com/CartoDB/gdal/files/694814/test_csvs.zip)

## Process
```
ogr2ogr --config CARTO_API_KEY myapikey -t_srs EPSG:4326 -f Carto "Carto:stephaniemongon" csvname.csv
```

## Expected result
* The_geom_webmercator column will be created
* The geom_webmercator will be automatically populated because latitude & longitude values are available and I'm specifying output projection in the CARTO Driver call

## Current result
(Checked via cdb manager & also https://stephaniemongon.carto.com/api/v2/sql?q=SELECT * FROM csvname&api_key=myapikey)

* Files import to my account but don't appear in my dashboard
* The imported files contain cartodb_id columns

stormevents_20161216:
![screen shot 2017-01-09 at 5 50 51 pm](https://cloud.githubusercontent.com/assets/1779444/21786900/4eb09bda-d694-11e6-8574-3a2cabe9e1aa.png)

stormevents_20161216_nogeom:
![screen shot 2017-01-09 at 5 52 16 pm](https://cloud.githubusercontent.com/assets/1779444/21786916/6579a8c0-d694-11e6-9334-79d432fbeb90.png)

vancouver_crime_2016:
![screen shot 2017-01-09 at 5 53 22 pm](https://cloud.githubusercontent.com/assets/1779444/21786957/889080e0-d694-11e6-9a18-8cdf0cc01f5f.png)

Maybe the issue is that we don't automatically "type & content guess" with GDAL CSV imports? 
* I noticed no the_geom column is created if there wasn't one in the original CSV, even if lat/lon columns are available
* BUT even though there's no inherent projection, in two of these CSV sources I already have the_geom column & I'm specifying output projection in the CARTO Driver call.

**Comment by rafatower** [comment]
@ztephm can you please post this issue in the upstream project? https://trac.osgeo.org/gdal

Also cc me there (`rtorre`) and Even Rouault (`rouault`)

cc/ @javisantana 

I'm closing ticket creation in this repo as it does not make sense any longer. It made sense at the time when we used our own patched version but that's not the case anymore.
